name: ppt
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # for design
  cupertino_icons: ^1.0.2
  lottie: ^2.4.0

  # for media
  audioplayers: ^4.1.0

  # for url
  url_launcher: ^6.1.11

  # for localization
  flutter_localizations:
    sdk: flutter

  # for internalization
  intl: ^0.18.0

  # device path
  path_provider: ^2.0.15
  shared_preferences: ^2.1.2
  permission_handler: ^10.3.0

  # hive database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.6

  # network connection
  connectivity_plus: ^4.0.1

  # dependency injection
  get_it: ^7.6.0

  # state management
  provider: ^6.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  flutter_lints: ^2.0.0

  # hive generate
  hive_generator: ^2.0.0

  # dart generator
  build_runner: ^2.4.5

  # json parsing
  json_serializable: ^6.7.0
  freezed: ^2.3.5

  # unit testing
  test: ^1.24.1
  mockito: ^5.4.2

flutter:

  uses-material-design: true
#  generate: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/audio/
    - assets/cars/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
